"""
Alerts API — Session 5.

Endpoints:
  GET  /api/alerts                     list alerts (filter: machine_id, status, limit)
  GET  /api/alerts/{alert_id}          get single alert
  POST /api/alerts/{alert_id}/approve  approve a pending alert
  POST /api/alerts/{alert_id}/reject   reject a pending alert
  GET  /api/alerts/stats               aggregate counts by severity / status
"""
from __future__ import annotations

from typing import Literal, Optional

from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel

router = APIRouter()


# ── Request / Response schemas ─────────────────────────────────────────────────

class ApproveRequest(BaseModel):
    approved_by: str = "human"


class RejectRequest(BaseModel):
    rejection_reason: str
    rejected_by: str = "human"


# ── Helpers ────────────────────────────────────────────────────────────────────

def _get_mongo(request: Request):
    db = getattr(request.app.state, "mongo_db", None)
    if db is None:
        raise HTTPException(status_code=503, detail="MongoDB unavailable")
    return db


def _get_orchestrator(request: Request):
    orch = getattr(request.app.state, "orchestrator", None)
    if orch is None:
        raise HTTPException(status_code=503, detail="Orchestrator not initialised")
    return orch


# ── Routes ─────────────────────────────────────────────────────────────────────

@router.get("")
async def list_alerts(
    request:    Request,
    machine_id: Optional[str]                          = None,
    status:     Optional[Literal["pending", "approved", "rejected"]] = None,
    limit:      int                                    = 20,
):
    """Return alerts, optionally filtered by machine_id and approval status."""
    db = _get_mongo(request)

    filt: dict = {}
    if machine_id:
        filt["machine_id"] = machine_id
    if status == "pending":
        filt["approved"] = None
    elif status == "approved":
        filt["approved"] = True
    elif status == "rejected":
        filt["approved"] = False

    cursor = db["alerts"].find(filt, {"_id": 0}).sort("created_at", -1).limit(limit)
    alerts = await cursor.to_list(length=limit)
    return {"alerts": alerts, "count": len(alerts)}


@router.get("/stats")
async def alert_stats(request: Request):
    """Aggregate alert counts by severity and approval status."""
    db = _get_mongo(request)

    pipeline = [
        {
            "$group": {
                "_id": {
                    "severity": "$root_cause_report.severity",
                    "approved": "$approved",
                },
                "count": {"$sum": 1},
            }
        },
        {"$sort": {"_id.severity": 1}},
    ]

    rows = await db["alerts"].aggregate(pipeline).to_list(length=100)

    # Shape into a more readable dict
    stats: dict = {}
    for row in rows:
        sev = row["_id"].get("severity", "UNKNOWN")
        approved = row["_id"].get("approved")
        status = "pending" if approved is None else ("approved" if approved else "rejected")
        stats.setdefault(sev, {})[status] = row["count"]

    return {"stats": stats}


@router.get("/{alert_id}")
async def get_alert(alert_id: str, request: Request):
    """Fetch a single alert by its UUID."""
    db = _get_mongo(request)
    doc = await db["alerts"].find_one({"alert_id": alert_id}, {"_id": 0})
    if doc is None:
        raise HTTPException(status_code=404, detail=f"Alert '{alert_id}' not found")
    return doc


@router.post("/{alert_id}/approve")
async def approve_alert(alert_id: str, body: ApproveRequest, request: Request):
    """
    Approve a pending alert.

    If the alert was generated by the orchestrator and has a thread_id,
    this also resumes the LangGraph pipeline.
    """
    db    = _get_mongo(request)
    doc   = await db["alerts"].find_one({"alert_id": alert_id}, {"_id": 0})
    if doc is None:
        raise HTTPException(status_code=404, detail=f"Alert '{alert_id}' not found")
    if doc.get("approved") is not None:
        raise HTTPException(
            status_code=409,
            detail=f"Alert already {'approved' if doc['approved'] else 'rejected'}",
        )

    # Update MongoDB directly
    from datetime import datetime, timezone
    await db["alerts"].update_one(
        {"alert_id": alert_id},
        {"$set": {
            "approved":     True,
            "approved_by":  body.approved_by,
            "approved_at":  datetime.now(tz=timezone.utc).isoformat(),
            "auto_approved": False,
        }},
    )

    # Resume orchestrator thread if available.
    # thread_id is not stored on the alert model; reconstruct it from machine_id + session_id,
    # which is how the orchestrator originally built it: f"{machine_id}:{session_id}".
    thread_id = doc.get("thread_id")
    if not thread_id:
        _mid = doc.get("machine_id")
        _sid = doc.get("session_id")
        if _mid and _sid:
            thread_id = f"{_mid}:{_sid}"

    if thread_id:
        try:
            orch = getattr(request.app.state, "orchestrator", None)
            if orch:
                await orch.resume(
                    thread_id,
                    approved=True,
                    approved_by=body.approved_by,
                )
        except Exception:
            pass  # Pipeline may have already completed

    return {"alert_id": alert_id, "status": "approved", "approved_by": body.approved_by}


@router.post("/{alert_id}/reject")
async def reject_alert(alert_id: str, body: RejectRequest, request: Request):
    """Reject a pending alert with a mandatory reason."""
    db  = _get_mongo(request)
    doc = await db["alerts"].find_one({"alert_id": alert_id}, {"_id": 0})
    if doc is None:
        raise HTTPException(status_code=404, detail=f"Alert '{alert_id}' not found")
    if doc.get("approved") is not None:
        raise HTTPException(
            status_code=409,
            detail=f"Alert already {'approved' if doc['approved'] else 'rejected'}",
        )

    from datetime import datetime, timezone
    await db["alerts"].update_one(
        {"alert_id": alert_id},
        {"$set": {
            "approved":          False,
            "approved_by":       body.rejected_by,
            "rejection_reason":  body.rejection_reason,
            "approved_at":       datetime.now(tz=timezone.utc).isoformat(),
        }},
    )

    # Resume orchestrator with rejection.
    # thread_id is not stored on the alert model; reconstruct from machine_id + session_id.
    thread_id = doc.get("thread_id")
    if not thread_id:
        _mid = doc.get("machine_id")
        _sid = doc.get("session_id")
        if _mid and _sid:
            thread_id = f"{_mid}:{_sid}"

    if thread_id:
        try:
            orch = getattr(request.app.state, "orchestrator", None)
            if orch:
                await orch.resume(
                    thread_id,
                    approved=False,
                    approved_by=body.rejected_by,
                    rejection_reason=body.rejection_reason,
                )
        except Exception:
            pass

    return {
        "alert_id":         alert_id,
        "status":           "rejected",
        "rejected_by":      body.rejected_by,
        "rejection_reason": body.rejection_reason,
    }
